version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1003
      - PGID=1004
      - TZ=CH
      - VERSION=docker
    volumes:
      - /dockermounts/plex:/config
      - /library:/library
    restart: unless-stopped
